radarlabs/radar-sdk-android

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
Android version of https://github.com/radarlabs/radar-sdk-ios/pull/49
> Reverse geocode current location

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
Android equivalent for https://github.com/radarlabs/radar-sdk-ios/pull/50
> Geocode Custom IP

- example/src/main/AndroidManifest.xml
- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconUtils.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarPermissionsHelper.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/model/RadarBeacon.kt
- sdk/src/main/java/io/radar/sdk/model/RadarEvent.kt
- sdk/src/main/java/io/radar/sdk/model/RadarUser.kt
A simple beacon implementation. iOS equivalent: https://github.com/radarlabs/radar-sdk-ios/pull/94
> [WIP] Beacons v1

- gradle/wrapper/gradle-wrapper.properties
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarActivityLifecycleCallbacks.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/model/RadarBeacon.kt
- sdk/src/main/java/io/radar/sdk/model/RadarEvent.kt
> Wrap Activity references in RadarActivityLifecycleCallbacks

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/test/java/io/radar/sdk/FusedLocationProviderClientMock.kt
See https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#getCurrentLocation(int,%20com.google.android.gms.tasks.CancellationToken)
> Use getCurrentLocation() instead of LocationRequest for trackOnce()

- sdk/build.gradle
- sdk/src/main/AndroidManifest.xml
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
- Listen for moving bubble exit transition
- Fix action names in `intent-filter`
- Add more logging
- Clear callbacks on timeout and remove unused `handler`
> More responsiveness improvements

- sdk/build.gradle
> bump version

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
To do:
- Testing
- Publish trackingOptions up to the server
> Server-controlled tracking options

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/model/RadarFraud.kt
- sdk/src/main/java/io/radar/sdk/model/RadarUser.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
- sdk/src/test/resources/track.json
Introduce RadarUser.mocked field and add RadarFraud object for simpler serialization.
> Add RadarUser.mocked field

- .circleci/config.yml
- .gitignore
- README.md
- example/build.gradle
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarApiHelper.kt
- sdk/src/main/java/io/radar/sdk/RadarLogger.kt
- sdk/src/main/java/io/radar/sdk/model/RadarLog.kt
- sdk/src/main/java/io/radar/sdk/util/Flushable.kt
- sdk/src/main/java/io/radar/sdk/util/RadarLogBuffer.kt
- sdk/src/main/java/io/radar/sdk/util/RadarSimpleLogBuffer.kt
- sdk/src/test/java/io/radar/sdk/RadarApiHelperMock.kt
- sdk/src/test/java/io/radar/sdk/matchers/RangeMatcher.kt
- sdk/src/test/java/io/radar/sdk/util/RadarSimpleLogBufferTest.kt
This reverts the changes from #155, however the changes will now be applied to the _develop_ branch, rather than _master_. Additionally, this uses chunking/streaming when sending logs, and does not write logs to the logger when sending a log request (this can cause memory issues)
> Add back logging (into develop branch)

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarBatteryManager.kt
- sdk/src/main/java/io/radar/sdk/RadarJobScheduler.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
- sdk/src/main/java/io/radar/sdk/util/BatteryState.kt
- sdk/src/test/java/io/radar/sdk/RadarBatteryManagerTests.kt
Add logging surrounding location events, jobs scheduled, and battery optimization states
> Add logging

- .github/workflows/radar-snapshot-action.yml
- buildSrc/build.gradle
- buildSrc/src/main/groovy/io/radar/ci/GitHubActions.groovy
- buildSrc/src/main/groovy/io/radar/ci/GitHubClient.groovy
- buildSrc/src/main/groovy/io/radar/ci/SnapshotDispatcher.groovy
- buildSrc/src/main/groovy/io/radar/mvnpublish/MavenServer.groovy
- buildSrc/src/main/groovy/io/radar/mvnpublish/RadarMavenPublishPluginExtension.groovy
- buildSrc/src/test/groovy/io/radar/ci/GitHubActionsTest.groovy
- buildSrc/src/test/groovy/io/radar/ci/SnapshotDispatcherTest.groovy
- buildSrc/src/test/groovy/io/radar/mvnpublish/RadarMavenPublishPluginTest.groovy
- sdk/build.gradle
Adds a GitHub action to automatically publish an SDK to maven central SNAPSHOTS when a branch is merged.
> Publish snapshots automatically

- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
This is used to determine path for handling new location/whether or not the location job needs to be scheduled
> Add check if foreground service is running

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
This reverts commit b6bc26ca5097b878d10b2cd872f26e2715e44a8b.
> Revert IMMUTABLE flag (#169) and update to SDK version 3.3.2

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- Uses more aggressive `ScanSettings`
- Fixes an issue where UUID-level scanning was not being used in the background even if enabled in project settings
> Beacons optimizations

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarGoogleLocationClient.kt
> Fix Play Services location crash on 21.0.0

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarGoogleLocationClient.kt
Fixes MOB-23
- Fixes a LocationManager lateinit exception
- Fixes a Bluetooth Adapter Exception on devices that do no support Bluetooth
- Uses `com.google.android.gms.location.LocationServices` to create `GeofencingClient` and `FusedLocationProviderClient`
> 3.5.7 release

- MIGRATION.md
- sdk/build.gradle
Migration guide for version 3.5.8
> 3.5.8 release

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
Story details: https://app.shortcut.com/radarlabs/story/11498
> sc-11498: Android SDK new trip APIs

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
- Exposes a new `startTrip` function that accepts `trackingOptions`.
> 3.5.9 release

- buildSrc/src/main/groovy/io/radar/mvnpublish/RadarNexusClient.groovy
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarApiHelper.kt
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
- sdk/src/main/java/io/radar/sdk/model/RadarReplay.kt
- sdk/src/main/java/io/radar/sdk/util/RadarReplayBuffer.kt
- sdk/src/main/java/io/radar/sdk/util/RadarSimpleReplayBuffer.kt
- sdk/src/test/java/io/radar/sdk/RadarApiHelperMock.kt
Just need to extend the timeout for replays before I'm ready to start building & testing
> Offline replay

- sdk/src/main/java/io/radar/sdk/Radar.kt
https://linear.app/radarlabs/issue/CORE-215/dont-fire-listeners-when-triggering-custom-events-android
> Don't fire event listeners for custom events

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/model/RadarAddress.kt
Completes both: https://linear.app/radarlabs/issue/INF-633/android-autocomplete-with-expandunits & https://linear.app/radarlabs/issue/INF-634/android-validate-address
> Validate address and expandUnits in autocomplete

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
Consistent with https://github.com/radarlabs/radar-sdk-ios/pull/256/files#diff-57a83f22ae98eebd6b400f6f7baecfb73b170d06629cbf8718e0a9000069d5a8R276
> don't replay if verified, bump version

- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
See: https://github.com/radarlabs/radar-sdk-ios/pull/287
> Add buffer to sync interval

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarVerificationManager.kt
- Case when searchBeacons does not return any beacons or uuids
> Send empty array for beacons to trigger exit events

- sdk/src/main/java/io/radar/sdk/model/RadarAddress.kt
- sdk/src/main/java/io/radar/sdk/model/RadarPlace.kt
- sdk/src/test/resources/search_places.json
Adding address field to place
Also patching `toJson` method as previously it was returning a NaN to the RN layer and causing an exception.
QA: was able to verify e2e flow with waypoint and recorded the logging:
> Add address field to place

- MIGRATION.md
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/model/RadarGeofence.kt
- sdk/src/main/java/io/radar/sdk/model/RadarGeofenceGeometry.kt
Changing interface for search geofence and making geometry an optional field for geofences.
> SDK changes for searchgeofences

- sdk/src/main/java/io/radar/sdk/model/RadarBeacon.kt
> Fix beacons parsing to json

- example/.gitignore
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
https://github.com/radarlabs/react-native-radar/pull/319
> 3.13.1 add onActivityCreate to support permission request from react-native

- example/src/main/AndroidManifest.xml
- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/AndroidManifest.xml
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarActivityManager.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/RadarState.kt
- sdk/src/main/java/io/radar/sdk/model/RadarSdkConfiguration.kt
- sdk/src/main/java/io/radar/sdk/model/RadarUser.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
- sdk/src/test/java/io/radar/sdk/model/RadarSdkConfigurationTest.kt
- sdk/src/test/resources/get_config_response.json
> Motion activity detection

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarVerificationManager.kt
Mirrors some improvements and simplifications in https://github.com/radarlabs/radar-sdk-ios/pull/406
> startTrackingVerified() improvements

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/model/RadarSdkConfiguration.kt
- sdk/src/test/java/io/radar/sdk/model/RadarSdkConfigurationTest.kt
apologies for the whitespace changes
> added syncAfterSetUser feature setting
