radarlabs/radar-sdk-android

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarLocationReceiver.kt
- sdk/src/main/java/io/radar/sdk/RadarUtils.kt
`JobScheduler` was added in Lollipop (API level 21): https://developer.android.com/reference/android/app/job/JobScheduler
Because of Doze Mode and because the process may occasionally get killed, we use `JobScheduler` to process geofence transitions and location updates on newer Android versions. `RadarJobScheduler` picks up these jobs and passes the location updates to `Radar.handleLocation()`.
Before passing location updates to `RadarJobScheduler`, we need to check whether we're on Lollipop or later. Pre-Lollipop, we can just pass location updates to `Radar.handleLocation()` immediately.
> Fix NoClassDefFoundError before Lollipop

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
iOS stores tracking option enum values as strings, whereas Android stores them as ints. This PR changes the Android SDK to store them as strings, while keeping backcompat.
In the JavaScript wrappers, this supports things like:
```
cordova.plugins.radar.startTrackingCustom({
desiredAccuracy: 'high',
sync: 'all',
replay: 'none'
});
> Support string values for enums in RadarTrackingOptions.fromJson()

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- Move `BluetoothAdapter` initialization after permission check
- Prevent extra `getContext()` and `trackOnce()` callback when permissions aren't granted (see #105)
> Move BluetoothAdapter initialization after permission check

- .github/workflows/radar-release-actions.yml
- .github/workflows/radar-snapshot-action.yml
- buildSrc/src/test/groovy/io/radar/ci/GitHubActionsTest.groovy
This ensures the SNAPSHOT env is configured when performing a Gradle build.
> Combine gradle tasks in github workflows:

- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
This saves an unnecessary API call if bluetooth permissions are not enabled.
> Add check before calling the searchBeacons call:

- sdk/build.gradle
- sdk/src/main/AndroidManifest.xml
- sdk/src/main/java/io/radar/sdk/RadarForegroundService.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
1. Add missing default RadarTrackingOptionsForegroundService usage. This allows a default notification to show, even when not customized by the app.
2. Remove the bond between the RadarForegroundService and the Activity Lifecycle. This ensures the app can continue tracking in CONTINUOUS mode even if the app activity is killed (or swiped).
3. Add channel customization and change the default name. This ensures all apps that use this SDK do not see "RadarSDK" as a user-facing String in Android's notification settings (see discussion and screenshots on slack).
> Small updates to FG Service

- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
Noticed when testing the new Remote Tracking Options feature that sometimes location updates would stop after detecting a stop and then moving again.
It turns out the logic on Android is a little different than iOS.  This change mirrors how iOS works, and adds logging statements to make it more obvious when bubble and synced geofences are removed.
> Don't remove the stopped bubble geofence in updateTracking() just because location is null

- .github/workflows/downstream-version-bump.yml
- Dispatch events to all downstream SDKs
- Add `platform: iOS` to client payload
> [9522] More downstream version bump changes

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarJobScheduler.kt
We need to make the [same change](https://github.com/radarlabs/radar-sdk-android/compare/3.3.3...3.4.0) we made in 3.4.0 to RadarJobScheduler
> Make sure Radar.initialize is called before any Radar members are called

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
- sdk/src/main/java/io/radar/sdk/RadarUtils.kt
There are some cases where `context.packageManager.hasSystemFeature(PackageManager.FEATURE_BLUETOOTH)` can return `true` but `BluetoothAdapter.getDefaultAdapter()` can return `null`. Previously we only guarded against the former being `false` but not against the latter. This fixes that and adds an initialization check in `stopRanging()` to be extra safe.
> Fix beacons crash caused by BluetoothAdapter.getDefaultAdapter() == null

- .github/workflows/downstream-version-bump.yml
Bump downstream SDK versions on `released` instead of `published`. See [these docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) for more context.
> [Automation] Bump Versions on Released instead of Published

- sdk/src/test/java/io/radar/sdk/RadarTest.kt
[sc-11338: [Android SDK] Add metadata checks for Radar.sendEvent() unit tests](https://app.shortcut.com/radarlabs/story/11338/android-sdk-add-metadata-checks-for-radar-sendevent-unit-tests)
* Added metadata assertions to the `Radar.sendEvent()` unit tests.
> sc-11338: Add metadata checks to custom RadarEvent unit tests

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
- sdk/src/test/resources/search_places_chain_metadata.json
[sc-11273: [Android SDK] Add a new chainMetadata param to searchPlaces in the Android SDK](https://app.shortcut.com/radarlabs/story/11273/android-sdk-add-a-new-chainmetadata-param-to-searchplaces-in-the-android-sdk)
* Adds a `chainMetadata` argument to `Radar.searchPlaces()`.
> sc-11273: Add a chainMetadata parameter to Radar.searchPlaces()

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarTripOptions.kt
[sc-11506: [Android SDK] Add approachingThreshold to Radar.startTrip() and .updateTrip()](https://app.shortcut.com/radarlabs/story/11506)
* Adds `RadarTripOptions.approachingThreshold`, which is passed as an `approachingThreshold` parameter when starting & updating trip calls.
> sc-11506: Add RadarTripOptions.approachingThreshold

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/RadarState.kt
- Exposes `Radar.setAnonymousTrackingEnabled()`. When enabled, avoids sending any stable device IDs, user IDs, or user metadata to `POST /track`
- TODO: Send current geofenceIds, placeId, and regionIds to avoid duplicate events
> support anonymous tracking

- sdk/src/main/java/io/radar/sdk/RadarBeaconManager.kt
Fixes an exception where a `lateinit` variable is getting set to null
> check adapter for null before initializing

- sdk/build.gradle
Upgrade `play-services-location` to `21.0.1`
Release notes for `play-services-location` [here](https://developers.google.com/android/guides/releases#november_03_2022).
> Upgrade play services location to 21.0.1

- MIGRATION.md
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- Upgrades `play-services-location` to 21.0.1
- Uses `foregroundServiceEnabled` to start and stop the foreground service
> 3.5.8 release

- .github/workflows/radar-release-actions.yml
- .github/workflows/radar-snapshot-action.yml
This PR does 2 things:
1) Stop publishing pre-releases as normal releases to maven
2) Publish SNAPSHOTs from pre-releases, not when merging to the `develop` branch
> publish SNAPSHOT releases from pre-releases not from pushing to develop

- sdk/src/main/java/io/radar/sdk/model/RadarGeofence.kt
- sdk/src/main/java/io/radar/sdk/model/RadarPlace.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
For https://linear.app/radarlabs/issue/MOB-77/surface-coordinates-from-search-geofences-call-in-rn
I've tested the iOS equivalent in the react native sample app. The android example app in the sdk runs with these changes, but I'm trying to verify that this works correctly on React Native on android. After that, I think we'd be good to go.
> Surface center, radius, and location for geofences & places

- sdk/src/main/java/io/radar/sdk/RadarTripOptions.kt
- sdk/src/test/java/io/radar/sdk/model/RadarTripOptionsTest.kt
Part of the work for https://linear.app/radarlabs/issue/MOB-56/include-trip-approaching-threshold-in-radartripoptions-helper
Haven't touched Kotlin code before so all the normal disclaimers apply. Also didn't see any obvious way to test this. Let's talk about testing and the rest of the cross platform dev concerns when we sesh @tjulien 
Working on the iOS part now.
> Include approachingThreshold in tripOptions

- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
There was a bug that reared it's head only if you were tracking with `replayed: stops`, failed a track call, and then changed to `replay: all` where the last call before changing to `all` would be sent up after clearing the replay buffer in the next successful `/track/replay`.
> Always clear last location if successful track

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarActivityLifecycleCallbacks.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
call `opened_app` when the app enters the foreground and whenever `sessionId` is updated
> Improve logic for `opened_app` conversions

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
The react native UI kit needs access to the host and publishable key. On iOS, we can access the `RadarSettings` directly,  but on Android it's an `internal object`. Exposing these in `Radar.kt` allows `react-native-radar` to get these values on Android.
> Expose getHost and getPublishableKey

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/src/main/java/io/radar/sdk/Radar.kt
This PR creates an endpoint that returns the string of the versioning of the sdk for parity with the IOS sdk.
the interface of the PR is 
`fun sdkVersion() : String`
QA:
Tested in example app to log versioning after initialization and was was successful.
> Expose versioning

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
Including side-effect of track once calls such that if the SDK's RTO are not in sync with the project's server side RTO, SDK will update its own RTO setting
QA:
steps: 
1. Have RTO turned off
2. check that RTO is not on in waypoint setting: 
3. turn on RTO to efficient in dashboard
4. call track once in waypoint and verify that it updated
5. modify RTO settings on dashboard and verify that it is propagated to waypoint after a calling trackOnce
6. turn off RTO on dashboard and call another trackonce on waypoint to verify that RTO is turned off
Follow up question, do we wish to introduce this side effect to the track verified calls and the mock tracking calls too?
> track once to modify tracking options

- example/build.gradle
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarActivityLifecycleCallbacks.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/RadarUtils.kt
- sdk/src/main/java/io/radar/sdk/RadarVerificationManager.kt
The corresponding server PR is [here](https://github.com/radarlabs/server/pull/5188).
* Bumps the Integrity API library
* Warms up the SDK in `Radar:initialize`
* Since the `googleCloudProjectNumber` is used in the warm-up, it doesn't need to be passed to `getIntegrityToken` 
* Split `.addOnCompleteListener` out to `. addOnSuccessListener` and `. addOnFailureListener` which is consistent with the library documentation 
LMK what you think!
It seems pretty fast! 
* `Execution time: 358 milliseconds to get standardIntegrityTokenProvider` - warm-up
* `Execution time: 147 milliseconds to request integrity token`
> migrate to Integrity API Standard Requests

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarForegroundService.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
We are adding a new field, `iconString` to the fields expected by the `setForgroundOptions` function. This allows the user to set the name of the asset they wish to use in the notification.
QA: 
The icon was changed to a bluetooth sign on waypoint
> Fix for set foreground service options icon

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarForegroundService.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
This PR adds the optional `iconColor` field to the `RadarTrackingOptionsForegroundService` data class that adds a background color to the notification of the foreground service notification. 
*QA*:
- We are able to successfully set background color on waypoint
- ![Screenshot_20231110_110055_Waypoint](https://github.com/radarlabs/radar-sdk-android/assets/139801512/180f58df-b3b3-45ac-8189-fda7534e380b)
- We do not break the existing code if no color is set 
- ![Screenshot_20231110_111424_Waypoint](https://github.com/radarlabs/radar-sdk-android/assets/139801512/825f914a-466a-4451-9e6c-3240b445644b)
- Setting a color without specifying a custom icon also works well as waypoint defaulted back to app icon.
- ![Screenshot_20231110_112232_Waypoint](https://github.com/radarlabs/radar-sdk-android/as …
> Add colour field to setForegroundOptions

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarNotificationHelper.kt
- sdk/src/main/java/io/radar/sdk/RadarNotificationOptions.kt
- sdk/src/main/java/io/radar/sdk/RadarNotificationsOptions.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt
- sdk/src/test/java/io/radar/sdk/RadarTest.kt
created a new SDK function `setNotificationOptions` that is used to set notification icon and color for event notifications and foreground service notifications. 
`iconString` and `iconColor` are fields that determine the icon and color of both kind of notificaitons.
They can be overriden by notification specific fields `foregroundServiceIconString`, `foregroundServiceIconColor`, `eventIconString`,`eventIconColor
QA:
Automated tests
Test for setter and getter, and defaulting to existing value tested in code
Manual tests
Setting with `iconString` and `iconColor` fields.
Setting with `foregroundServiceIconString`, `foregroundServiceIconColor`, `eventIconString`,`eventIconColor` and Setting with `foregroundServiceIconString`, `foregroundServiceIconColor`, `iconString` and `iconColor` …
> setNotificationsOptions end point

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/model/RadarEvent.kt
The confidence field of the event object was not being converted to a json object correctly, this causes issues with the RN sdk not being able to show this field.
The enumeration to int conversion is fixed in this PR.
QA:
This Android sdk is installed in waypoint and a single `trackOnce` is called with its results printed. Note how the events in the events array have the confidence field now.
> Fix conversion of confidence enum to int

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
Currently, the `TrackVerified` call assumes that a valid `googlePlayProjectNumber` is stored in `RadarSettings`. However, if this assumption is false for whatever reason, the function will proceed with the default  `googlePlayProjectNumber` value of 0, which will cause a crash with the google play service. 
This PR adds a check to abort the track verified call if `RadarSettings.getGooglePlayProjectNumber(this.context)` returns 0, indicating that the `googlePlayProjectNumber` value has not been set. 
QA: 
Previously, an attempt to call `trackVerified` on staging on android caused a crash, but with this check the `trackVerified` fails gracefully.
> Prevent crash with fraud when googlePlayProject is not set.

- MIGRATION.md
- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
This PR deprecates the `expandUnits` param for autocomplete and adds `mailable`
> expandUnits -> mailable

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarUtils.kt
- `valid` check failed to filter out 0 coordinates previously due to `longitude` and `latitude` values not being precisely 0
> Ignore 0 values of latitude and longitude on client

- MIGRATION.md
- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
- sdk/src/main/java/io/radar/sdk/RadarVerificationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarVerifiedReceiver.kt
- sdk/src/main/java/io/radar/sdk/model/RadarEvent.kt
- sdk/src/main/java/io/radar/sdk/model/RadarGeofence.kt
- sdk/src/main/java/io/radar/sdk/model/RadarReplay.kt
- sdk/src/main/java/io/radar/sdk/model/RadarVerifiedLocationToken.kt
- sdk/src/main/java/io/radar/sdk/util/BatteryState.kt
- sdk/src/main/java/io/radar/sdk/util/Flushable.kt
- sdk/src/main/java/io/radar/sdk/util/JobMapper.kt
- sdk/src/main/java/io/radar/sdk/util/RadarFileStorage.kt
- sdk/src/main/java/io/radar/sdk/util/RadarLogBuffer.kt
- sdk/src/main/java/io/radar/sdk/util/RadarReplayBuffer.kt
- sdk/src/main/java/io/radar/sdk/util/RadarSimpleLogBuffer.kt
- sdk/src/main/java/io/radar/sdk/util/RadarSimpleReplayBuffer.kt
Android equivalent of https://github.com/radarlabs/radar-sdk-ios/pull/337
- Remove `trackVerifiedToken()` and change `trackVerified()` to return `RadarVerifiedLocationToken`
- Remove `token` param from `startTrackingVerified()` and change `RadarVerifiedDelegate` to return `RadarVerifiedLocationToken`
- Make `token.expiresAt` override `interval` if needed
- Add `getVerifiedLocationToken()` which will return last token if not expired and request fresh token if needed
- Random logging and comment cleanup to match iOS
> Track verified callbacks

- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarLogger.kt
Changes in this PR:
- we only want to perform past termination checks for users who are RadarLogLevel.DEBUG
- we only need to check for past termination when the activity is created in the foreground.
> fix for crash from logPastTermination

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarSettings.kt
https://linear.app/radarlabs/issue/FENCE-2088/default-log-level-to-none-for-production-projects
clean up the code path for flushing log buffer, we want to flush whenever we do have logs. the default log level for live is NONE and for test is INFO, which are set from the server via remote SDK config.
> enable logging on live projects, default log level to NONE on live

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarForegroundService.kt
tested with example app that passing in importance = 0 result in importance = 0 for foreground service, and not passing in importance = 0 defaults to importance = 3
> allow 0 importance for radar foreground service

- example/src/main/java/io/radar/example/MainActivity.kt
- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarLocationManager.kt
- sdk/src/main/java/io/radar/sdk/RadarTripOptions.kt
Allows you to pass `tripOptions.startTracking = NO` to not automatically start tracking. The default remains that tracking starts automatically.
Starting tracking also doesn't happen automatically if `trackingOptions.startTrackingAfter` is non-nil.
We explicitly check the local tracking options for `startTrackingAfter` and `stopTrackingAfter` so that RTO can be used in conjunction with these local tracking options.
Finally, we make sure that if you call `Radar.stopTracking()` after having started tracking with a `trackingOption.startTrackingAfter`, that tracking remains off until `Radar.startTracking()` is called again.
> Allow for createTrip without starting tracking immediately

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/RadarApiClient.kt
- sdk/src/main/java/io/radar/sdk/RadarApiHelper.kt
- sdk/src/main/java/io/radar/sdk/model/RadarSdkConfiguration.kt
- sdk/src/test/java/io/radar/sdk/model/RadarSdkConfigurationTest.kt
We do 2 things here:
- for all tracks we include the `updatedAtMsDiff`, which will be used to determine the `location.updatedAt`
- we modify `updatedAtMsDiff` in `RadarAPIHelper` to update `updatedAtMsDiff` at request time, as `updatedAtMsDiff` is meant to represent the difference between the client request time and the timestamp of the location processed by the SDK. This is an important fix to locations being replayed as previously their `updatedAtMsDiff` was determined by their original (failed) request time — not actually the time at successful request.
> Replay time ordering

- sdk/build.gradle
- sdk/src/main/java/io/radar/sdk/Radar.kt
- sdk/src/main/java/io/radar/sdk/RadarVerificationManager.kt
- adds `desiredAccuracy` param to `trackVerified()` and `getVerifiedLocationToken()` (default is `MEDIU `, whereas `startTrackingVerified()` always uses `HIGH`)
- adds `clearVerifiedLocationToken()`
- refactors some logic in `RadarVerificationManager`
- when calling `startTrackingVerified()`, if the last token is already valid, avoid an extra request and simply schedule the next interval check
iOS PR: https://github.com/radarlabs/radar-sdk-ios/pull/427
> make desiredAccuracy configurable, avoid double request, add clearVerifiedLocationToken()
